# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# Refer to https://github.com/toml-lang/toml for detailed TOML docs.

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# To build for 0.3.0
# [[constraint]]
#   name = "github.com/rexray/gocsi"
#   revision = "9407f5f4ed38592fe11b57c1c9d3621df05b753b"

# [[constraint]]
#   name = "github.com/thecodeteam/goscaleio"
#   revision = "30be8284b32e1a53e2ac473e95275b24e6d583de"
